services:
  hugo:
    image: klakegg/hugo:0.123.1.0-ext-alpine
    ports:
     - 1313:1313
    volumes:
     - .:/src/gatling.io-doc-theme
     - /src/gatling.io-doc-theme/resources/
     - /src/gatling.io-doc-theme/node_modules/
    environment:
      - HUGO_ENV=development
    working_dir: /src/gatling.io-doc-theme
    entrypoint: "bash -c 'hugo mod npm pack && npm install && pwd && ls . && cd exampleSite && pwd && ls . && hugo server --buildDrafts'"
